---
- hosts: database
  roles:
    - mysql

- hosts: wordpress
  handlers:
      - name: restart apache
        service:
          name: apache2
          state: restarted
        become: yes
  roles:
    - webserver
    - wordpress