---
- name: 'Download wordpress config file'
  get_url:
    url: https://wordpress.org/wordpress-4.9.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Unarchive wordpress file'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copy sample file to origi'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Config wp-config.php with databases entries'     
  template:
      src: 'templates/wp-config.php.j2'
      dest: "{{ wp_installation_dir }}/wp-config.php"
  become: yes

- name: 'Copy default.conf to remote server'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache