---
- name: 'Install packages'
  apt:  
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: "Create mysql"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: "Create user to {{ wp_db_name }}"
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_wordpress }}"
    
- name: 'Config mysql to accept remote connections'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql